name: Download

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File Name'
        required: true
      url:
        description: 'File URL'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
            node-version: 18

      - name: Replace URL
        run: sed -i 's/文件的URL/${{ inputs.url }}/g' script.js

      - name: Replace Name
        run: sed -i 's/文件名/${{ inputs.filename }}/g' script.js

      - name: Run script
        run: node script.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          path: ${{ github.workspace }}/download
